name: CI workflow

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest  #Github runner(free)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Docker Setup
        uses: docker/setup-buildx-action@v1 